x-db-env: &db_env
  POSTGRES_USER: $PG_USER
  POSTGRES_PASSWORD: $PG_PASSWORD
  POSTGRES_DB: $PG_DB

x-backend-env: &backend_env
  METRICS_TOKEN: $METRICS_TOKEN
  TESTING: false
  DB_USER: $PG_USER
  DB_PASSWORD: $PG_PASSWORD
  DB_NAME: $PG_DB
  DB_HOST: db
  DB_PORT: 5432
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_DB: 0
  JWT_SECRET_KEY: $JWT_SECRET_KEY
  MAIL_USERNAME: $MAIL_USERNAME
  MAIL_PASSWORD: $MAIL_PASSWORD
  MAIL_FROM: $MAIL_FROM
  MAIL_PORT: $MAIL_PORT
  MAIL_SERVER: $MAIL_SERVER
  MAIL_STARTTLS: $MAIL_STARTTLS
  MAIL_SSL_TLS: $MAIL_SSL_TLS
  MAIL_USE_CREDENTIALS: $MAIL_USE_CREDENTIALS
  MAIL_VALIDATE_CERTS: $MAIL_VALIDATE_CERTS

x-nginx-end: &nginx_env
  DOMAIN: $DOMAIN

services:
  webserver:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment: *nginx_env
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app_network
    depends_on:
      - api

  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    environment: *db_env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: eqalpha/keydb:x86_64_v6.3.4
    container_name: redis
    networks:
      - app_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend
    container_name: api
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000
    environment: *backend_env
    networks:
      - app_network
    depends_on:
      - db
      - redis

  taskiq_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend
    container_name: taskiq_worker
    command: taskiq worker src.core.tiq:broker -fsd
    environment: *backend_env
    networks:
      - app_network
    depends_on:
      - db
      - redis

  taskiq_scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend
    container_name: taskiq_scheduler
    command: taskiq scheduler src.core.tiq:scheduler --update-interval 5
    environment: *backend_env
    networks:
      - app_network
    depends_on:
      - redis

volumes:
  postgres_data:

networks:
  app_network:
    external: true
