"""Added view logs

Revision ID: ce79333bb08c
Revises: 012dd508921f
Create Date: 2026-06-24 17:05:24.645698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce79333bb08c'
down_revision: Union[str, Sequence[str], None] = '012dd508921f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_logs',
    sa.Column('object_type', sa.String(length=255), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id', 'user_id', name='uq_view_logs_object_user')
    )
    op.create_index(op.f('ix_view_logs_user_id'), 'view_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_logs_user_id'), table_name='view_logs')
    op.drop_table('view_logs')
    # ### end Alembic commands ###
